{% set version = "7.6.2" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  path: ../../


build:
  number: 0
  binary_relocation: false [osx]
  script_env:
    - OCCT_VERSION={{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - ninja
    - cmake
    - rapidjson
    - swig >=3.0.11

  host:
    - python
    - occt =={{ version }}
    - numpy >=1.17
    - rapidjson

  run:
    - python
    - occt =={{ version }}
    - six
    - rapidjson
    - numpy >=1.17

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
  requires:
#    - pyqt >=5
    - mypy
    - svgwrite
#    - wxpython >=4
#    - pyside2 >=5

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
