[workspace]
name = "pythonocc-core"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[feature.prod.tasks]
test = { cmd = ["pytest", "tests"], description = "Run the test suite with pytest" }

[feature.conda.tasks]
conda = { cmd = "rattler-build build -r ci/conda/recipe.yaml", description = "Run the test suite with pytest" }


[environments]
prod = { features = ["prod"], solve-group = "prod", no-default-feature = true }
conda = { features = ["conda"], solve-group = "conda", no-default-feature = true }

[feature.conda.dependencies]
rattler-build = "*"

[feature.prod.dependencies]
occt = "==7.9.1"
python = "*"
ninja = "*"
cmake = "*"
swig = "==4.3.1"
pytest = "*"

