from enum import IntEnum
from typing import overload, NewType, Optional, Tuple

from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.IVtkOCC import *
from OCC.Core.IVtk import *


class IVtkTools_ShapeDataSource(vtkPolyDataAlgorithm):
    def __init__(self, x: IVtkTools_ShapeDataSource, (: IVtkTools_ShapeDataSource) -> None: ...
    def FastTransformModeOff(self) -> None: ...
    def FastTransformModeOn(self) -> None: ...
    def GetId(self) -> IVtk_IdType: ...
    def GetShape(self) -> False: ...
    def SubShapeIDs(self) -> False: ...

class IVtkTools_ShapeObject(vtkDataObject):
    def __init__(self, x: IVtkTools_ShapeObject, (: IVtkTools_ShapeObject) -> None: ...
    @overload
    def GetShapeSource(self) -> IVtkTools_ShapeDataSource: ...
    @overload
    def SetShapeSource(self, theDataSource: IVtkTools_ShapeDataSource) -> None: ...
    @staticmethod
    def getKey() -> False: ...

class IVtkTools_ShapePicker(vtkAbstractPropPicker):
    def __init__(self, x: IVtkTools_ShapePicker, (: IVtkTools_ShapePicker) -> None: ...
    def GetTolerance(self) -> False: ...

class IVtkTools_SubPolyDataFilter(vtkPolyDataAlgorithm):
    def __init__(self, x: IVtkTools_SubPolyDataFilter, (: IVtkTools_SubPolyDataFilter) -> None: ...
    @overload
    def AddData(self, theSet: IVtk_IdTypeMap) -> None: ...
    @overload
    def AddData(self, theIds: IVtk_ShapeIdList) -> None: ...
    def Clear(self) -> None: ...
    @overload
    def SetData(self, theSet: IVtk_IdTypeMap) -> None: ...
    @overload
    def SetData(self, theIds: IVtk_ShapeIdList) -> None: ...
    def SetIdsArrayName(self, theArrayName: str) -> None: ...

class IVtkTools_DisplayModeFilter(IVtkTools_SubPolyDataFilter):
    def __init__(self, x: IVtkTools_DisplayModeFilter, (: IVtkTools_SubPolyDataFilter) -> None: ...
    def FaceBoundaryDraw(self) -> False: ...
    def GetDisplayMode(self) -> IVtk_DisplayMode: ...
    def IsSmoothShading(self) -> False: ...
    def MeshTypesForMode(self, theMode: IVtk_DisplayMode) -> IVtk_IdTypeMap: ...
    def SetDisplayMode(self, aMode: IVtk_DisplayMode) -> None: ...
    def SetMeshTypesForMode(self, theMode: IVtk_DisplayMode, theMeshTypes: IVtk_IdTypeMap) -> None: ...

# harray1 classes
# harray2 classes
# hsequence classes

IVtkTools_ShapeObject_GetOccShape = IVtkTools_ShapeObject.GetOccShape
IVtkTools_ShapeObject_GetShapeSource = IVtkTools_ShapeObject.GetShapeSource
IVtkTools_ShapeObject_SetShapeSource = IVtkTools_ShapeObject.SetShapeSource
IVtkTools_ShapeObject_SetShapeSource = IVtkTools_ShapeObject.SetShapeSource
IVtkTools_ShapeObject_getKey = IVtkTools_ShapeObject.getKey
